version: '3.9'

services:
  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:latest
    ports:
      - "6379:6379"