version: '3.9'

services:
  demo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${APP_HOST_PORT:-8080}:${APP_CONTAINER_PORT:-8080}"
    depends_on:
      - mysql-dev
      - redis-dev
      - insert-data
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    environment:
      REDIS_HOST: "${REDIS_HOST:-redis-dev}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      REDIS_PASS: "${REDIS_PASS:-}"
      MYSQL_HOST: "${MYSQL_HOST:-mysql-dev}"
      MYSQL_PORT: "${MYSQL_PORT:-3306}"
      MYSQL_USER: "${MYSQL_USER:-root}"
      MYSQL_PASS: "${MYSQL_PASS:-password}"
      LOAD_ON_STARTUP: "${LOAD_ON_STARTUP:-true}"
    entrypoint: ["wait-for-it.sh","${MYSQL_HOST}:${MYSQL_PORT}","-t","30","--","java","-Dserver.port=${APP_CONTAINER_PORT:-8080}","-jar","/app/hibernatedemo.jar"]
    networks:
      - hibernate-demo-network

  insert-data:
    build:
      context: ./setup
      dockerfile: Dockerfile
    depends_on:
      - mysql-dev
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    entrypoint: [ "wait-for-it.sh","${MYSQL_HOST}:${MYSQL_PORT}","--","python3","${SCRIPT_NAME}" ]
    environment:
      MYSQL_HOST: "${MYSQL_HOST:-mysql-dev}"
      MYSQL_PORT: "${MYSQL_PORT:-3306}"
      MYSQL_DB: "${MYSQL_DB:-testdb}"
      MYSQL_USER: "${MYSQL_USER:-boot}"
      MYSQL_PASS: "${MYSQL_PASS:-password}"
      NUM_ITEMS: "${NUM_ITEMS:-10000}"
    networks:
      - hibernate-demo-network

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS:-password}"
      MYSQL_DATABASE: "${MYSQL_DB:-testdb}"
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    networks:
      - hibernate-demo-network

  redis-dev:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    networks:
      - hibernate-demo-network

networks:
  hibernate-demo-network:
    name: hibernate-demo-network
    driver: bridge