version: '3.9'

services:
  demo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${APP_HOST_PORT:-8080}:${APP_CONTAINER_PORT:-8080}"
    depends_on:
      - mysql-dev
      - redis-dev
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    environment:
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306
      LOAD_ON_STARTUP: "true"
    entrypoint: ["wait-for-it.sh","${MYSQL_HOST}:${MYSQL_PORT}","--","java","-Dserver.port=8080","-jar","/app/hibernatedemo.jar"]
    networks:
      - hibernate-demo-network

  insert-data:
    build:
      context: ./setup
      dockerfile: Dockerfile
    depends_on:
      - mysql-dev
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    # NOTE - also need to update $MYSQL_HOST, $MYSQL_PORT, and $SCRIPT_NAME in .env
    entrypoint: [ "wait-for-it.sh","${MYSQL_HOST}:${MYSQL_PORT}","--","python3","${SCRIPT_NAME}" ]
    environment:
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306
      MYSQL_DB: testdb
      MYSQL_USER: root
      MYSQL_PASS: password
      NUM_ITEMS: 100000
    networks:
      - hibernate-demo-network

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    networks:
      - hibernate-demo-network

  redis-dev:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hibernate-demo-network

networks:
  hibernate-demo-network:
    name: hibernate-demo-network
    driver: bridge