version: '3.9'

services:
  demo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql-dev
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      MYSQL_HOST: mysql-dev
      MYSQL_PORT: 3306

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:latest
    ports:
      - "6379:6379"